Controllers/CarController.cs
using Learing_Core.Data;
using Learing_Core.Models;
using Learing_Core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Learing_Core.Controllers
{

    public class CarController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CarController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            //To get All cars so it for sell or for rent
            var car = _context.car.Include(c => c.Company).Include(r => r.RentalCar).ToList();
            return View(car);
        }

        [HttpGet]
        public IActionResult Create()
        {
            //Get all company and rent and gallery to fill it in Combobox
            var company = _context.company.ToList();
            var rentalCar = _context.rentalCar.ToList();
            var gallery = _context.gallery.ToList();
            var viewModel = new CarViewModel
            {
                RentalCar = rentalCar,
                Company = company,
                Galleries = gallery,
                RentalCarId = null
            };
            return View(viewModel);
        }

        [HttpPost][ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CarViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Add new car
                var car = new Car
                {
                    Name = model.Name,
                    Description = model.Description,
                    Car_Model = model.Car_Model,
                    CompanyId = model.CompanyId,
                    ContactNumbr = model.ContactNumbr,
                    Price = model.Price,
                    RentalCarId = model.RentalCarId,
                    CarImage1 = uploadImage(model.CarImage1, 0),
                    CarImage2 = uploadImage(model.CarImage2, 1),
                    CarImage3 = uploadImage(model.CarImage3, 2),
                    GalleryId = model.GalleryId,
                };
                await _context.car.AddAsync(car);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
           
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var car = await _context.car.FindAsync(id);
            if (car == null)
                return NotFound();
            //Fill Combobox
            var company = _context.company.ToList();
            var rentalCar = _context.rentalCar.ToList();
            var gallery = _context.gallery.ToList();

            var viewModel = new CarViewModel
            {
                Name = car.Name,
                Description = car.Description,
                Car_Model = car.Car_Model,
                CompanyId = car.CompanyId,
                ContactNumbr = car.ContactNumbr,
                Price = car.Price,
                RentalCarId = car.RentalCarId,
                CarImage1 = car.CarImage1,
                CarImage2 = car.CarImage2,
                CarImage3 = car.CarImage3,
                GalleryId = car.GalleryId,
                RentalCar = rentalCar,
                Company = company,
                Galleries = gallery,
            };
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CarViewModel model)
        {
            var car = await _context.car.FindAsync(id);
            if (car == null)
                return NotFound();
            //Fill car changed information
            car.Name = model.Name;
            car.Description = model.Description;
            car.Car_Model = model.Car_Model;
            car.CompanyId = model.CompanyId;
            car.ContactNumbr = model.ContactNumbr;
            car.Price = model.Price;
            car.RentalCarId = model.RentalCarId;
            car.GalleryId = model.GalleryId;
            // Check if there change in the image 
            if(uploadImage(model.CarImage1, 0) != null)
                car.CarImage1 = uploadImage(model.CarImage1, 0);
            if(uploadImage(model.CarImage2, 1) != null)
                car.CarImage2 = uploadImage(model.CarImage2, 1);
            if(uploadImage(model.CarImage3, 2) != null)
                car.CarImage3 = uploadImage(model.CarImage3, 2);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            //Find car by id and get it detalis
            var car = await _context.car.FindAsync(id);
            if (car == null)
                return NotFound();

            return View(car);
        }

        public ActionResult Search(string searchTerm)
        {
            if (string.IsNullOrEmpty(searchTerm))
            {
                // If the search term is empty, return all Cars
                return RedirectToAction("Index");
            }

            // Search for Car by ID or name
            var car = _context.car.Where(c =>
                c.Id.ToString().Contains(searchTerm) ||
                c.Name.ToLower().Contains(searchTerm)
            );

            return View("Index", car);
        }
        //Add image file
        public byte[] uploadImage(byte[] image,int index)
        {
            // Check how many files are being send
            if (Request.Form.Files.Count > 0)
            {
                var file = Request.Form.Files.ToList();//Get the first file
                using (var memory = new MemoryStream())
                {
                    file[index].CopyToAsync(memory);
                    image = memory.ToArray();
                }
            }
            return image;
        }

    }
}

Controllers/CompanyController.cs
using Learing_Core.Data;
using Learing_Core.Models;
using Learing_Core.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;

namespace Learing_Core.Controllers
{
    [Authorize(Roles ="Admin")]
    public class CompanyController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CompanyController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task< IActionResult> Index()
        {
            //Get all Companies in Db
            var company = _context.company.ToList();
            return View(company);
        }

        public async Task<IActionResult> Details(int id)
        {
            //Get Company info by id
            var company = await _context.company.FindAsync(id);
            if(company == null)
                return NotFound();
            return View(company);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CompanyViewModel model)
        {
            if (!ModelState.IsValid)
                return View();
            //Add New Company
            var company = new Company()
            {
                Name = model.Name,
                Description = model.Description,
                CompanyLogo = uploadImage(model.CompanyLogo),
            };

            await _context.company.AddAsync(company);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //Get company by id to fill the form with it infromation
            var company= await _context.company.FindAsync(id);
            var viewModel = new CompanyViewModel
            {
                Name = company.Name,
                Description = company.Description,
                CompanyLogo = company.CompanyLogo,
            };
            return View(viewModel);
        }


        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CompanyViewModel model)
        {
            //Check if company existis 
            var company = await _context.company.FindAsync(id);
            if (company == null)
                return NotFound();
            //Update Company information
            company.Name = model.Name;
            company.Description = model.Description;
            if(uploadImage(model.CompanyLogo) != null)
                company.CompanyLogo = uploadImage(model.CompanyLogo);

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public ActionResult Search(string searchTerm)
        {
            if (string.IsNullOrEmpty(searchTerm))
            {
                // If the search term is empty, return all Companies
                return RedirectToAction("Index");
            }
            // Search for Company by ID or name
            var company = _context.company.Where(c =>
                c.Id.ToString().Contains(searchTerm) ||
                c.Name.ToLower().Contains(searchTerm)
            );

            return View("Index", company);
        }
        public byte[] uploadImage(byte[] image)
        {
            // Check how many files are being send
            if (Request.Form.Files.Count > 0)
            {
                var file = Request.Form.Files.FirstOrDefault();//Get the first file
                using (var memory = new MemoryStream())
                {
                    file.CopyToAsync(memory);
                    image = memory.ToArray();
                }
            }
            return image;
        }

    }
}

Controllers/RolesController.cs
using Learing_Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Learing_Core.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            this._roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var role = await _roleManager.Roles.ToListAsync();
            return View(role);
        }
    }
}

Controllers/UsersController.cs
using Learing_Core.Models;
using Learing_Core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Learing_Core.Controllers
{
    //[Authorize(Roles ="Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManger;
        private readonly RoleManager<IdentityRole> _roleManger;
        public UsersController(UserManager<ApplicationUser> userManger, RoleManager<IdentityRole> roleManger)
        {
            this._userManger = userManger;
            this._roleManger = roleManger;
        }
        public async Task<IActionResult> Index()
        {
            var users = await _userManger.Users.Select(user => new UserViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                UserName = user.UserName,
                Email = user.Email,
                Roles = _userManger.GetRolesAsync(user).Result
            }).ToListAsync();

            return View(users);
        }
        public async Task<IActionResult> Add()
        {
            return View();
        }
            [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddUserViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }
            if (await _userManger.FindByEmailAsync(model.Email) != null)
            {
                ModelState.AddModelError("Email", "This email is already exists");
                return View(model);
            }
            if(await _userManger.FindByNameAsync(model.UserName) != null)
            {
                ModelState.AddModelError("UserName", "This user name is already exists");
            }

            var user = new ApplicationUser
            {
                UserName = model.UserName,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
            };
            var result  = await _userManger.CreateAsync(user,model.Password);
            if(!result.Succeeded)
            {
                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return View(model);
            }
            await _userManger.AddToRoleAsync(user, "User");
            return View(model);
        }

        public async Task<IActionResult> Edit(string userId)
        {
            var user = await _userManger.FindByIdAsync(userId);
            if(user == null)
                return NotFound();

            var viewModel = new EditUserViewModel
            {
                Id = userId,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                UserName = user.UserName
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var user = await _userManger.FindByIdAsync(model.Id);
            if (user == null)
                return NotFound();

            var userWithSameName = await _userManger.FindByNameAsync(model.UserName);
            if (userWithSameName != null && userWithSameName.Id != model.Id)
            {
                ModelState.AddModelError("UserName", "There is user with the same userName exists");
                return View(model);
            }

            var userWithSameEmail = await _userManger.FindByEmailAsync(model.Email);
            if(userWithSameEmail != null && userWithSameEmail.Id != model.Id)
            {
                ModelState.AddModelError("Email", "There is user with the same Email exists");
                return View(model);
            }
            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.Email = model.Email;
            user.UserName = model.UserName;
            await _userManger.UpdateAsync(user);
            return RedirectToAction(nameof(Index));
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Learing_Core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/page2.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Learing_Core.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid .top">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Carly</a>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Cars for Sell</a>
                        </li>

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index">Cars</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Index">Company</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Gallery" asp-action="Index">Gallery</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

        <div class="modal" tabindex="-1" role="dialog" id="form-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer start-->
    <footer>
        <section class="contact">
            <div class="content">
                <h2>Contact Us</h2>
                <p>Let us know if there something on your mind</p>
            </div>
            <div class="contain">
                <div class="contactInfo">
                    <div class="box">
                        <div class="icon"><img src="~/Images//location.png" alt="" height="30px" width="30px"></div>
                        <div class="text">
                            <h3>Address</h3>
                            <p>Yemen-Mukklla<br>Fuah,MainRoad</p>
                        </div>
                    </div>
                    <div class="box">
                        <div class="icon"><img src="~/Images//phone.png" alt="" height="30px" width="30px"></div>
                        <div class="text">
                            <h3>Phone</h3>
                            <p>+967 773-792-408</p>
                        </div>
                    </div>
                    <div class="box">
                        <div class="icon"><img src="~/Images//email-532-433830.png" alt="" height="30px" width="30px"></div>
                        <div class="text">
                            <h3>Email</h3>
                            <p>ale305450@gmail.com</p>
                        </div>
                    </div>
                    <h2 class="txt">Connect with us</h2>
                    <ul class="sci">
                        <li><a href="#"><img src="~/Images/facebook.png" alt="" height="30px" width="30px"></a></li>
                        <li><a href="#"><img src="~/Images//whatsapp.png" alt="" height="30px" width="30px"></a></li>
                        <li><a href="#"><img src="~/Images//tiwterFooter.png" alt="" height="30px" width="30px"></a></li>
                        <li><a href="#"><img src="" alt=""></a></li>
                    </ul>
                </div>

                <div class="contactForm">
                    <form>
                        <h2>Send Message</h2>
                        <div class="inputBox">
                            <input type="text" name="" required="required">
                            <span>Full Name</span>
                        </div>
                        <div class="inputBox">
                            <input type="text" name="" required="required">
                            <span>Email</span>
                        </div>
                        <div class="inputBox">
                            <textarea required="required"></textarea>
                            <span>Type your Message...</span>
                        </div>
                        <div class="inputBox">
                            <input type="submit" value="Send">
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </footer>
    <!-- Footer End-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootbox.js/bootbox.min.js"></script>
    <script src="~/lib/DataTables/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>